name: Changeset Check

on:
  pull_request:
    branches:
      - main

jobs:
  changeset-check:
    name: Check Changeset
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install --frozen-lockfile || bun install
        
      - name: Check for Changeset
        run: bunx changeset status --since origin/${{ github.base_ref }}