name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.19
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Build packages
      run: bun run build
    
    - name: Run linting
      run: bun run lint
    
    - name: Run type checking
      run: bun run typecheck
    
    - name: Run core and CLI tests
      run: |
        echo "Running core package tests..."
        bun test packages/core
        echo "Running CLI package tests..." 
        bun test packages/cli
      env:
        CI: true
    
    - name: Run integration tests (allow some failures)
      run: bun test packages/tests
      env:
        CI: true
      continue-on-error: true
    
    - name: Test CLI generation
      run: |
        # Generate a test server to verify CLI works end-to-end
        bun run dev --input ../tests/src/fixtures/simple-api.json --out ./test-output --name ci-test-server --runtime bun --force
        # Verify server file was generated
        test -f ./test-output/mcp-server/index.ts
        echo "✅ MCP server generated successfully"
      working-directory: packages/cli
      env:
        CI: true
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          packages/*/test-*.json
          packages/*/coverage/
        retention-days: 7